### ISSUE TITLE
New version of RMCob/homebridge-wyze-connected-home-op published. V0.5.6

### ISSUE THREAD

**Issue by RMCob** [misenhower/homebridge-wyze-connected-home#49]
I have updated RMCob/homebridge-wyze-connected-home-op to incorporate the fixes for the 403 error and Color Bulb functionality supplied by others. I do not have a Color Bulb to verify those changes but the 403 error is definitely fixed (until something else changes :-))

**Comment by SteveQ2** [comment]
I am using your implementation and it is working on my local network.  However, whenever my iPhone is away from home and connects to different network, your homebridge plugin crashes and I have to do a complete reinstall of my Wyze homebridge instance.  I probably have an issue with my network setup but nevertheless I don't think such a catastrophic crash should occur! Any suggestions?

Steve

[homebridge.log.txt](https://github.com/misenhower/homebridge-wyze-connected-home/files/6969860/homebridge.log.txt)

**Comment by SteveQ2** [comment]
Here is the log after the plugin crashes.
[homebridge.log (1).txt](https://github.com/misenhower/homebridge-wyze-connected-home/files/6970918/homebridge.log.1.txt)

**Comment by RMCob** [comment]
Steve, I looked at your log file. I am not familiar with running Homebridge on Windows so I really can't help much. The paths shown in the log file that have the component 'Roaming'. Is there a non-Roaming version? Also you said you had to do a complete re-install of the Homebridge instance. From the log file it looks like it just re-started. Is that what you meant? Perhaps someone else running Homebridge under Windows could chime in?

**Comment by RMCob** [comment]
Steve, in your second log file, in the beginning are the lines:
[8/11/2021, 2:18:43 PM] [Wyze] Request failed: Error: getaddrinfo ENOTFOUND api.wyzecam.com
[8/11/2021, 2:18:43 PM] [Wyze] Error, refreshing access token and trying again
[8/11/2021, 2:48:00 PM] Error: send EHOSTUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:429:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[8/11/2021, 2:48:00 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[8/11/2021, 2:48:05 PM] [HB Supervisor] Restarting Homebridge...

You definitely have a network issue there. The plugin at first connected to wyze.com and got a list of all your devices. Then when it restarted it couldn't connect to wyze.com to get the device list so all the previous devices were 'orphaned' and therefor it tried to remove them from Homebridge. I can see what happened but I don't know what to tell you to do to fix the problem in Windows.... :-(

**Comment by SteveQ2** [comment]
So I left home and when I came back, the plugin had crashed.  The second logfile is what appears when it has crashed.  To recover, i must now uninstall and reinstall my homebridge instance and reinstall all the devices.

**Comment by SteveQ2** [comment]
I have 2 other instances of homebridge running with a total of 87 non "wyze" devices.  These instances are rock solid for the past year.  The wyze plugin is on the same network and configured pretty much the same.  What is the "access token"?

**Comment by SteveQ2** [comment]
RM, I have RMCob/homebridge-wyze-connected-home-op  plugin running in a separate Homebridge instance named homebridge-four on port 8584.  All the wyze specific device information is stored in a windows directory  named .homebridge-four  the access token is in the "persist" sub directory.  It appears the plugin is not looking in the right file location when it restarts!

Steve

**Comment by SteveQ2** [comment]
A power outage forced me to reinstall HomeBridge and the Wyze plugin.  I got everything working and all was good for about 4 days. Then the Wyze connected home RMCob plugin crashed.  Very frustrating!

Is anyone using the Wyze connected home plugin successfully?

**Comment by SteveQ2** [comment]
Still having problems. I thought running the plugin as a child had solved the problem. Nope!
![Screenshot (8)](https://user-images.githubusercontent.com/72275254/131014366-1a283d8c-357b-4815-9968-aa65a2023fba.png)
